baseURL = 'https://leoth.dev/'
languageCode = 'en-us'
title = 'LeothDev'
theme = "rose-pine"

enableRobotsTXT = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[languages]
  [languages.en]
    contentDir = 'content'
    languageName = 'English'
    weight = 10

[menu]
  [[menu.header]]
    name = "about"
    url = "about"

  [[menu.header]]
    name = "posts"
    url = "posts/"

  [[menu.header]]
    name = "projects"
    url = "projects/"

  [[menu.header]]
    name = "werewolf.sh"
    url = "werewolf.sh/"

  [[menu.header]]
    name = "boomarks"
    url = "bookmarks/"

[params]
  author = "Leoth"
  description = "My devlog and projects"
  hostname = "leoth.dev"
  mainSections = ["posts"]

  [[params.social]]
    key = "github"
    name = "GitHub"
    url = "https://github.com/LeothDev"

  [[params.social]]
    key = "youtube"
    name = "YouTube"
    url = "https://www.youtube.com/@LeothDev"

  [[params.social]]
    key = "mastodon"
    name = "mastodon"
    url = "https://mastodon.social/@leothdev"
