baseURL = 'https://leoth.dev/'
languageCode = 'en-us'
title = 'LeothDev'
theme="rose-pine"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[languages]
  [languages.en]
    contentDir = 'content'
    languageName = 'English'
    weight = 10

